defaults:
  - _self_
  - data: default
  - wandb: default
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

random_forest:
  n_estimators: 200          # Increased from 100 for better convergence
  max_depth: 15              # Limited to prevent overfitting given feature count
  min_samples_split: 5       # Increased to reduce noise sensitivity
  min_samples_leaf: 2        # Slightly increased for better generalization
  max_features: 0.33         # About 35 features per tree (1/3 of 106)
  bootstrap: true           
  class_weight: null # "balanced"   # Recommended unless you know class distribution is balanced
  n_jobs: -1
  random_state: 42
  verbose: 0

logistic_regression:
  max_iter: 1000            # Increased to ensure convergence
  multi_class: 'multinomial' # Uses softmax for multi-class
  class_weight: null # or 'balanced'   # Handle class imbalance
  solver: 'lbfgs'           # Efficient solver for multinomial LR
  n_jobs: -1
  random_state: 42
  verbose: 0

debug: false
debug_args:
  on_adata: false
  resample_adata: true

seed: 42
output_dir: "benchmarks"
run_bulk_expression_rf: true
run_bulk_expression_lr: true
run_h3type_rf: true
run_h3type_lr: true

hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.id}