defaults:
  - _self_
  - data: default
  - wandb: default
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

random_forest:
  n_estimators: 100
  max_depth: null  # null for unlimited depth
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: "sqrt"
  bootstrap: true
  class_weight: null # or "balanced"
  n_jobs: -1
  random_state: 42
  verbose: 0

debug: false
seed: 42
output_dir: "benchmarks"
run_bulk_expression: true
run_h3type: true